# Generated by Django 5.0.4 on 2024-05-02 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Definitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('language', models.CharField(choices=[('english', 'ENGLISH'), ('spanish', 'SPANISH'), ('french', 'FRENCH'), ('german', 'GERMAN'), ('italian', 'ITALIAN'), ('portuguese', 'PORTUGUESE')], max_length=20)),
                ('reading_level', models.IntegerField(choices=[(1, 'FIRST_GRADE'), (2, 'SECOND_GRADE'), (3, 'THIRD_GRADE'), (4, 'FOURTH_GRADE'), (5, 'FIFTH_GRADE'), (6, 'SIXTH_GRADE'), (7, 'SEVENTH_GRADE'), (8, 'EIGHTH_GRADE'), (9, 'NINTH_GRADE'), (10, 'TENTH_GRADE'), (11, 'ELEVENTH_GRADE'), (12, 'TWELFTH_GRADE'), (13, 'COLLEGE'), (14, 'ADULT')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='api.terms')),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('session_id', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to='api.terms')),
            ],
        ),
    ]
